Feature/rh 2 homepage
Stixor-Technologies/rehm-hof pull request #3
Opened 2024-05-22 07:14 UTC by fawadmehmood1

# Description

Please include a summary of the changes and the related issue.

- Completed homepage

## Type of change

Please select type of issue addressed,

- [ ] New feature ( RH-2 ) 

# Dependences / Libraries Installed

Please list the packages and libraries installed (if any)

- [ ] ( @gsap/react) 
- [ ] (react-fast-marquee)

# How Has This Been Tested By The Developer?

- Verified if the ui is according to figma

# Checklist:

- [ ] I have performed a self review of my code.

- [ ] I have removed consoles, debuggers and unnecessary code blocks.

- [ ] My code follows the style guidelines of this project

- [ ] My changes generate no new warnings or errors

- [ ] I have commented my code, particularly in hard-to-understand areas

- [ ] New and existing unit tests pass locally with my changes

- [ ] Any dependent changes have been merged and published in downstream modules

- [ ] I understand that I am accountable for any code added in this PR, and any negative impact will effect my performance evaluation

2024-05-22 08:25 UTC, imrankhan-stixor requested changes

2024-05-22 08:25 UTC, imrankhan-stixor commented on app/(landing-page)/page.tsx
> +      {/* section# 1*/}
remove this

2024-05-22 08:25 UTC, imrankhan-stixor commented on app/(landing-page)/page.tsx
> +                className="mx-auto transition-transform duration-500 group-hover:translate-y-[-55%] group-hover:scale-[1.15]"
use -translate for negative movement

2024-05-22 08:25 UTC, imrankhan-stixor commented on app/(landing-page)/page.tsx
> +                className="mx-auto transition-transform duration-500 group-hover:translate-y-[-55%] group-hover:scale-[1.15]"
same here

2024-05-22 08:25 UTC, imrankhan-stixor commented on app/(landing-page)/page.tsx
> +      {/* section# 2 */}
remove

2024-05-22 08:25 UTC, imrankhan-stixor commented on app/(landing-page)/page.tsx
> +      {/* section# 3 */}
remove

2024-05-22 08:25 UTC, imrankhan-stixor commented on app/(landing-page)/page.tsx
> +        <section className="relative z-10 bg-bone bg-opacity-50">
why are two relative used here, remove one if not needed

2024-05-22 08:25 UTC, imrankhan-stixor commented on app/(landing-page)/page.tsx
> +            <div className="mt-[3.563rem] lg:order-1 lg:w-[50%] lg:max-w-[47.5rem] 2xl:w-full">
use w-3/6 instead of w-[50%]

2024-05-22 08:25 UTC, imrankhan-stixor commented on app/(landing-page)/page.tsx
> +              <h2 className="text-[clamp(1.6rem,2.4vw,2.813rem)] text-primary sm:w-[50%] lg:w-[70%] 2xl:w-full 2xl:leading-[3.813rem]">
here as well

2024-05-22 08:25 UTC, imrankhan-stixor commented on app/(landing-page)/page.tsx
> +                  <span className="town-houses-tag">STADTHÄUSER</span>
what are these two classes doing? can't seem to find them in tailwind

2024-05-22 08:25 UTC, imrankhan-stixor commented on app/(landing-page)/page.tsx
> +        {/* section# 4 */}
remove

2024-05-22 08:25 UTC, imrankhan-stixor commented on app/(landing-page)/page.tsx
> +            <Image src={InnenraumStaffel} width={760} height={494} alt="" />
add alt message

2024-05-22 08:25 UTC, imrankhan-stixor commented on app/(landing-page)/page.tsx
> +              <Image src={Building} alt="" />
add alt message

2024-05-22 08:25 UTC, imrankhan-stixor commented on app/(landing-page)/page.tsx
> +              <Image src={Bildergruppe} alt="" className="h-full" />
add alt message

2024-05-22 08:25 UTC, imrankhan-stixor commented on app/(landing-page)/page.tsx
> +      {/* section# 5 */}
remove

2024-05-22 08:25 UTC, imrankhan-stixor commented on app/(landing-page)/page.tsx
> +          alt=""
add alt message

2024-05-22 08:25 UTC, imrankhan-stixor commented on app/(landing-page)/page.tsx
> +      {/* section# 6 */}
remove

2024-05-23 04:26 UTC, fawadmehmood1 commented on app/(landing-page)/page.tsx
> +      {/* section# 1*/}
@imrankhan-stixor , The comments are there to help us easily identify which section of code corresponds to which part of the layout.

2024-05-23 04:35 UTC, fawadmehmood1 commented on app/(landing-page)/page.tsx
> +        <section className="relative z-10 bg-bone bg-opacity-50">
they both have different purpose

2024-05-23 04:37 UTC, fawadmehmood1 commented on app/(landing-page)/page.tsx
> +                  <span className="town-houses-tag">STADTHÄUSER</span>
same styling is applied to multiple elements, that's why these utility classes are here.

2024-05-23 05:46 UTC, imrankhan-stixor approved these changes

2024-05-23 05:46 UTC, merged